highlighter: pygments
#markdown: kramdown
#gems:
#  - jekyll-redirect-from
#  - jekyll-sitemap
#  - jekyll-mentions

#include:
#  - _static
#  - _modules

NIGHTLY_VERSION: "0.3.1-SNAPSHOT"
STABLE_VERSION: "0.3.0"
SPARK_VERSION0: "1.4.1"
SPARK_VERSION1: "1.3.1"
PHANTOMJS_VERSION: "1.9.8"
SCALA_BINARY_VERSION: "2.10"
SCALA_VERSION: "2.10.4"
